In [3]:
#Question1
A =[1, 2, 3, 4, 5]
B = [6, 7, 8]
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
#Question2
import numpy as np
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#Question3
import pandas as pd
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
fuel_data = pd.read_csv(url)
fuel_data.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

In [15]:
#Question3
import pandas as pd
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
fuel_data = pd.read_csv(url)
Lowest_pdul = fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].mean()
Lowest = Lowest_pdul.where(Lowest_pdul == Lowest_pdul.min()).dropna()
print(Lowest )

fuel_type_code_pudl
gas    13.659397
Name: fuel_cost_per_unit_burned, dtype: float64


In [29]:
#Question4
starnds = fuel_data["fuel_mmbtu_per_unit"].std()
_75th_perc= fuel_data["fuel_mmbtu_per_unit"].quantile(0.75)

print("std = ","{:.2f}".format(starnds))
print("75th_perc = ","{:.2f}".format(_75th_perc))


std =  10.60
75th_perc =  17.01


In [30]:
#Question5
skwness = fuel_data["fuel_qty_burned"].skew()
kurtosis = fuel_data["fuel_qty_burned"].kurt()

print("skew = ","{:.2f}".format(skwness))
print("kurt = ","{:.2f}".format(kurtosis))

skew =  15.85
kurt =  651.37


In [60]:
#Question6&7
missing_tot = fuel_data.isnull().sum()
counts = fuel_data.count()[0]
if counts > 0:
    percent_missing = missing_tot* 100 / counts
    print("total missing values = " ,missing_tot.where(missing_tot>0).dropna().values[0])
    print("percentage_of_missing_values = ","{:.3f}".format(percent_missing.where(percent_missing>0).dropna().values[0]))
else:
    print("No Data")


total missing values =  180.0
percentage_of_missing_values =  0.610


In [72]:
#Question8
fuel_data.corr().sum()
# fuel_mmbtu_per_unit             0.716298 and fuel_qty_burned                 0.850576 and 

utility_id_ferc1                0.920774
report_year                     1.005239
fuel_qty_burned                 0.850576
fuel_mmbtu_per_unit             0.716298
fuel_cost_per_unit_burned       0.957737
fuel_cost_per_unit_delivered    0.967851
fuel_cost_per_mmbtu             1.008057
dtype: float64

In [122]:
#Question9
fuel_data.groupby(['fuel_type_code_pudl','report_year'])['fuel_cost_per_unit_burned'].sum()
group_fuel = fuel_data.groupby(['fuel_type_code_pudl','report_year'])['fuel_cost_per_unit_burned'].sum()
_coal = group_fuel["coal"]
sum_coal = sum(_coal)
percentage_1994 = _coal[1994]*100 / sum_coal
percentage_1998 = _coal[1998]*100 / sum_coal
change = abs(percentage_1994 - percentage_1998)
print("he percentage change in the fuel cost per unit burned in 1998 compared to 1994 = ","{:.2f}".format(change),"%")

he percentage change in the fuel cost per unit burned in 1998 compared to 1994 =  0.53 %


In [103]:
#Question10
group = fuel_data.groupby('report_year')['fuel_cost_per_unit_delivered'].mean()
the_highest_value = group.max()
element = group.where(group == the_highest_value ).dropna()
print(" Year has the highest average fuel cost per unit delivered is ",element.index[0])

 Year has the highest average fuel cost per unit delivered is  1997
